name: 'build'

on:
  push:
  pull_request:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make clean
    - run: make
    - run: make test
